// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Data         = require("../common/data.js");
var Util         = require("../common/util/util.js");
var Curry        = require("bs-platform/lib/js/curry.js");
var Express      = require("bs-express/lib/js/src/express.js");
var Make         = require("express");
var Calc_bans    = require("./calc_bans.js");
var Util_promise = require("../common/util/util_promise.js");

function from_p(f) {
  return (function (req, res, next) {
      var out = Curry._3(f, req, res, next);
      return out.catch((function () {
                    return Util_promise.pure(res.send("Error occurred"));
                  }));
    });
}

var app = Make();

var dir = (process.cwd());

var day = 1000 * 60 * 60 * 24;

function current_time() {
  return new Date().getTime();
}

var current_data = [/* record */[
    /* heroes : [] */0,
    /* details : [] */0,
    /* time */0
  ]];

app.get("/ban-data", from_p((function (_, res, _$1) {
            var partial_arg = Data.Hero_data[/* to_json */1];
            return Curry._2(Util_promise.$less$$great, (function (param) {
                          return Util.$percent((function (param) {
                                        return res.send(param);
                                      }), partial_arg, param);
                        }), current_data[0][/* time */2] + day < new Date().getTime() ? Util_promise.$great$great$eq(Calc_bans.get_all_hero_details(/* () */0), (function (data) {
                                current_data[0] = data;
                                return Util_promise.pure(data);
                              })) : Util_promise.pure(current_data[0]));
          })));

app.use("/static", Make.static(dir + "/static", Curry._1(Express.Static[/* defaultOptions */0], /* () */0)));

app.get("/", (function (_, res, _$1) {
        return res.sendFile(Util.debug(dir + "/static/index.html"), undefined);
      }));

app.listen(3000);

exports.from_p       = from_p;
exports.app          = app;
exports.dir          = dir;
exports.day          = day;
exports.current_time = current_time;
exports.current_data = current_data;
/* app Not a pure module */
