// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var Util_kernel = require("./util_kernel.js");

function debug(v) {
  console.log(v);
  return v;
}

function $$const(x, _) {
  return x;
}

function on(c, f, a, b) {
  return Curry._2(c, Curry._1(f, a), Curry._1(f, b));
}

function neg(f, x) {
  return 1 - Curry._1(f, x);
}

var flip = Util_kernel.flip;

var $percent = Util_kernel.compose;

var compose = Util_kernel.compose;

exports.debug    = debug;
exports.flip     = flip;
exports.$percent = $percent;
exports.compose  = compose;
exports.$$const  = $$const;
exports.on       = on;
exports.neg      = neg;
/* No side effect */
