// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

var Curry      = require("bs-platform/lib/js/curry.js");
var Util_monad = require("./util_monad.js");

function $great$great$eq(m, f) {
  return m.then(Curry.__1(f));
}

function pure(prim) {
  return Promise.resolve(prim);
}

var Base = /* module */[
  /* >>= */$great$great$eq,
  /* pure */pure,
  /* map_impl : Define_using_bind */-349054340
];

var include = Util_monad.Monad_make(Base);

var map_impl = /* Define_using_bind */-349054340;

var $great$great = include[0];

var $eq$less$less = include[1];

var map = include[2];

var $less$$great = include[3];

var ap = include[4];

var $less$neg$great = include[5];

var sequence = include[6];

var sequence_ = include[7];

var mapM = include[8];

var mapM_ = include[9];

exports.Base            = Base;
exports.$great$great$eq = $great$great$eq;
exports.pure            = pure;
exports.map_impl        = map_impl;
exports.$great$great    = $great$great;
exports.$eq$less$less   = $eq$less$less;
exports.map             = map;
exports.$less$$great    = $less$$great;
exports.ap              = ap;
exports.$less$neg$great = $less$neg$great;
exports.sequence        = sequence;
exports.sequence_       = sequence_;
exports.mapM            = mapM;
exports.mapM_           = mapM_;
/* include Not a pure module */
