// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Util        = require("../../src/common/util/util.js");
var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var Bs_mocha    = require("../bs_mocha.js");
var Caml_obj    = require("bs-platform/lib/js/caml_obj.js");
var Util_list   = require("../../src/common/util/util_list.js");
var Caml_int32  = require("bs-platform/lib/js/caml_int32.js");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Util_option = require("../../src/common/util/util_option.js");

Bs_mocha.from_pair_suites("Util", /* :: */[
      /* tuple */[
        "flip works",
        (function () {
            return /* Eq */Block.__(0, [
                      2,
                      Util.flip((function (prim, prim$1) {
                              return prim - prim$1 | 0;
                            }), 1, 3)
                    ]);
          })
      ],
      /* :: */[
        /* tuple */[
          "const works",
          (function () {
              return /* Eq */Block.__(0, [
                        1,
                        Util.$$const(1, "foo")
                      ]);
            })
        ],
        /* :: */[
          /* tuple */[
            "% works",
            (function () {
                return /* Eq */Block.__(0, [
                          "5",
                          Util.$percent(Pervasives.string_of_int, (function (param) {
                                  return 2 + param | 0;
                                }), 3)
                        ]);
              })
          ],
          /* :: */[
            /* tuple */[
              "% works deeply",
              (function () {
                  return /* Eq */Block.__(0, [
                            -2,
                            Util.$percent((function (param) {
                                    return Util.$percent((function (param) {
                                                  return 4 - param | 0;
                                                }), (function (param) {
                                                  return (param << 1);
                                                }), param);
                                  }), (function (param) {
                                    return 1 + param | 0;
                                  }), 2)
                          ]);
                })
            ],
            /* :: */[
              /* tuple */[
                "on works",
                (function () {
                    return /* Eq */Block.__(0, [
                              3,
                              Util.on((function (prim, prim$1) {
                                      return prim - prim$1 | 0;
                                    }), Caml_format.caml_int_of_string, "5", "2")
                            ]);
                  })
              ],
              /* :: */[
                /* tuple */[
                  "neg works when true",
                  (function () {
                      return /* Eq */Block.__(0, [
                                /* false */0,
                                Util.neg((function (param) {
                                        return Caml_obj.caml_equal(1, param);
                                      }), 1)
                              ]);
                    })
                ],
                /* :: */[
                  /* tuple */[
                    "neg works when true",
                    (function () {
                        return /* Eq */Block.__(0, [
                                  /* true */1,
                                  Util.neg((function (param) {
                                          return Caml_obj.caml_equal(2, param);
                                        }), 1)
                                ]);
                      })
                  ],
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

function incr_if_pos(n) {
  var match = +(n > 0);
  if (match !== 0) {
    return /* Some */[n + 1 | 0];
  } else {
    return /* None */0;
  }
}

Bs_mocha.from_pair_suites("Util.List", /* :: */[
      /* tuple */[
        "hd works on non-empty lists",
        (function () {
            return /* Eq */Block.__(0, [
                      /* Some */[1],
                      Util_list.hd(/* :: */[
                            1,
                            /* :: */[
                              2,
                              /* :: */[
                                3,
                                /* [] */0
                              ]
                            ]
                          ])
                    ]);
          })
      ],
      /* :: */[
        /* tuple */[
          "hd doesn't error on empty lists",
          (function () {
              return /* Eq */Block.__(0, [
                        /* None */0,
                        Util_list.hd(/* [] */0)
                      ]);
            })
        ],
        /* :: */[
          /* tuple */[
            "tl works on non-empty lists",
            (function () {
                return /* Eq */Block.__(0, [
                          /* Some */[/* :: */[
                              2,
                              /* :: */[
                                3,
                                /* [] */0
                              ]
                            ]],
                          Util_list.tl(/* :: */[
                                1,
                                /* :: */[
                                  2,
                                  /* :: */[
                                    3,
                                    /* [] */0
                                  ]
                                ]
                              ])
                        ]);
              })
          ],
          /* :: */[
            /* tuple */[
              "tl works on empty lists",
              (function () {
                  return /* Eq */Block.__(0, [
                            /* None */0,
                            Util_list.tl(/* [] */0)
                          ]);
                })
            ],
            /* :: */[
              /* tuple */[
                "nth works on valid indexes",
                (function () {
                    return /* Eq */Block.__(0, [
                              /* Some */[2],
                              Util_list.nth(/* :: */[
                                    1,
                                    /* :: */[
                                      2,
                                      /* :: */[
                                        3,
                                        /* [] */0
                                      ]
                                    ]
                                  ], 1)
                            ]);
                  })
              ],
              /* :: */[
                /* tuple */[
                  "nth works when it goes off the end of the list",
                  (function () {
                      return /* Eq */Block.__(0, [
                                /* None */0,
                                Util_list.nth(/* :: */[
                                      1,
                                      /* :: */[
                                        2,
                                        /* :: */[
                                          3,
                                          /* [] */0
                                        ]
                                      ]
                                    ], 5)
                              ]);
                    })
                ],
                /* :: */[
                  /* tuple */[
                    "nth works on negative indexes",
                    (function () {
                        return /* Eq */Block.__(0, [
                                  /* None */0,
                                  Util_list.nth(/* :: */[
                                        1,
                                        /* :: */[
                                          2,
                                          /* :: */[
                                            3,
                                            /* [] */0
                                          ]
                                        ]
                                      ], -1)
                                ]);
                      })
                  ],
                  /* :: */[
                    /* tuple */[
                      "nth doesn't cause stack overflow",
                      (function () {
                          return /* Eq */Block.__(0, [
                                    /* Some */[1],
                                    Util_list.nth(Util_list.replicate(10000, 1), 9999)
                                  ]);
                        })
                    ],
                    /* :: */[
                      /* tuple */[
                        "minimal append works",
                        (function () {
                            return /* Eq */Block.__(0, [
                                      /* :: */[
                                        1,
                                        /* :: */[
                                          2,
                                          /* :: */[
                                            3,
                                            /* :: */[
                                              4,
                                              /* :: */[
                                                5,
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ],
                                      Util_list.append(/* :: */[
                                            1,
                                            /* :: */[
                                              2,
                                              /* [] */0
                                            ]
                                          ], /* :: */[
                                            3,
                                            /* :: */[
                                              4,
                                              /* :: */[
                                                5,
                                                /* [] */0
                                              ]
                                            ]
                                          ])
                                    ]);
                          })
                      ],
                      /* :: */[
                        /* tuple */[
                          "append works",
                          (function () {
                              var lengths = Util_list.range(/* Some */[0], 11);
                              var expected_list = Util_list.replicate(10, 1);
                              var expected = Curry._2(Util_list.map, (function (param) {
                                      return Util.$$const(expected_list, param);
                                    }), lengths);
                              var actual = Util_list.map2((function (n1, n2) {
                                      return Util_list.append(Util_list.replicate(n1, 1), Util_list.replicate(n2, 1));
                                    }), lengths, Util_list.rev(lengths));
                              return /* Eq */Block.__(0, [
                                        expected,
                                        actual
                                      ]);
                            })
                        ],
                        /* :: */[
                          /* tuple */[
                            "append doesn't cause stack overflow",
                            (function () {
                                return /* Eq */Block.__(0, [
                                          20000,
                                          Util_list.length(Util_list.append(Util_list.replicate(10000, 1), Util_list.replicate(10000, 1)))
                                        ]);
                              })
                          ],
                          /* :: */[
                            /* tuple */[
                              "minimal map works",
                              (function () {
                                  return /* Eq */Block.__(0, [
                                            /* :: */[
                                              2,
                                              /* :: */[
                                                3,
                                                /* :: */[
                                                  4,
                                                  /* [] */0
                                                ]
                                              ]
                                            ],
                                            Curry._2(Util_list.map, (function (param) {
                                                    return 1 + param | 0;
                                                  }), /* :: */[
                                                  1,
                                                  /* :: */[
                                                    2,
                                                    /* :: */[
                                                      3,
                                                      /* [] */0
                                                    ]
                                                  ]
                                                ])
                                          ]);
                                })
                            ],
                            /* :: */[
                              /* tuple */[
                                "map works",
                                (function () {
                                    var lengths = Util_list.range(/* Some */[1], 11);
                                    var f = function (x) {
                                      return x + 1 | 0;
                                    };
                                    var init = Curry._2(Util_list.map, (function (eta) {
                                            return Util_list.range(/* None */0, eta);
                                          }), lengths);
                                    var expected = Curry._2(Util_list.map, (function (n) {
                                            return Util_list.range(/* Some */[1], n + 1 | 0);
                                          }), lengths);
                                    var actual = Curry._2(Util_list.map, Curry._1(Util_list.map, f), init);
                                    return /* Eq */Block.__(0, [
                                              expected,
                                              actual
                                            ]);
                                  })
                              ],
                              /* :: */[
                                /* tuple */[
                                  "map doesn't cause stack overflow",
                                  (function () {
                                      return /* Eq */Block.__(0, [
                                                10000,
                                                Util_list.length(Curry._2(Util_list.map, (function (a) {
                                                            return a;
                                                          }), Util_list.replicate(10000, 1)))
                                              ]);
                                    })
                                ],
                                /* :: */[
                                  /* tuple */[
                                    "fold_right works",
                                    (function () {
                                        return /* Eq */Block.__(0, [
                                                  Util_list.range(/* None */0, 4),
                                                  Util_list.fold_right((function (a, b) {
                                                          return /* :: */[
                                                                  a,
                                                                  b
                                                                ];
                                                        }), Util_list.range(/* None */0, 4), /* [] */0)
                                                ]);
                                      })
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      "fold_right doesn't cause stack overflow",
                                      (function () {
                                          return /* Eq */Block.__(0, [
                                                    10000,
                                                    Util_list.fold_right((function (prim, prim$1) {
                                                            return prim + prim$1 | 0;
                                                          }), Util_list.replicate(10000, 1), 0)
                                                  ]);
                                        })
                                    ],
                                    /* :: */[
                                      /* tuple */[
                                        "concat works",
                                        (function () {
                                            return /* Eq */Block.__(0, [
                                                      /* :: */[
                                                        1,
                                                        /* :: */[
                                                          2,
                                                          /* :: */[
                                                            3,
                                                            /* :: */[
                                                              0,
                                                              /* :: */[
                                                                1,
                                                                /* :: */[
                                                                  2,
                                                                  /* :: */[
                                                                    -1,
                                                                    /* :: */[
                                                                      0,
                                                                      /* :: */[
                                                                        1,
                                                                        /* [] */0
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ],
                                                      Util_list.concat(/* :: */[
                                                            Util_list.range(/* Some */[1], 4),
                                                            /* :: */[
                                                              Util_list.range(/* None */0, 3),
                                                              /* :: */[
                                                                Util_list.range(/* Some */[-1], 2),
                                                                /* [] */0
                                                              ]
                                                            ]
                                                          ])
                                                    ]);
                                          })
                                      ],
                                      /* :: */[
                                        /* tuple */[
                                          "concat on few long lists doesn't cause stack overflow",
                                          (function () {
                                              return /* Eq */Block.__(0, [
                                                        30000,
                                                        Util_list.length(Util_list.concat(Util_list.replicate(3, Util_list.replicate(10000, 1))))
                                                      ]);
                                            })
                                        ],
                                        /* :: */[
                                          /* tuple */[
                                            "concat on many short lists doesn't cause stack overflow",
                                            (function () {
                                                return /* Eq */Block.__(0, [
                                                          30000,
                                                          Util_list.length(Util_list.concat(Util_list.replicate(10000, Util_list.replicate(3, 1))))
                                                        ]);
                                              })
                                          ],
                                          /* :: */[
                                            /* tuple */[
                                              "map_concat works",
                                              (function () {
                                                  return /* Eq */Block.__(0, [
                                                            /* :: */[
                                                              1,
                                                              /* :: */[
                                                                1,
                                                                /* :: */[
                                                                  1,
                                                                  /* :: */[
                                                                    2,
                                                                    /* :: */[
                                                                      2,
                                                                      /* :: */[
                                                                        2,
                                                                        /* [] */0
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ],
                                                            Util_list.map_concat((function (param) {
                                                                    return Util_list.replicate(3, param);
                                                                  }), /* :: */[
                                                                  1,
                                                                  /* :: */[
                                                                    2,
                                                                    /* [] */0
                                                                  ]
                                                                ])
                                                          ]);
                                                })
                                            ],
                                            /* :: */[
                                              /* tuple */[
                                                "map_concat doesn't cause stack overflow on long results",
                                                (function () {
                                                    return /* Eq */Block.__(0, [
                                                              30000,
                                                              Util_list.length(Util_list.map_concat((function (param) {
                                                                          return Util_list.replicate(10000, param);
                                                                        }), /* :: */[
                                                                        1,
                                                                        /* :: */[
                                                                          2,
                                                                          /* :: */[
                                                                            3,
                                                                            /* [] */0
                                                                          ]
                                                                        ]
                                                                      ]))
                                                            ]);
                                                  })
                                              ],
                                              /* :: */[
                                                /* tuple */[
                                                  "map_concat doesn't cause stack overflow on long inputs",
                                                  (function () {
                                                      return /* Eq */Block.__(0, [
                                                                30000,
                                                                Util_list.length(Util_list.map_concat((function (param) {
                                                                            return Util_list.replicate(3, param);
                                                                          }), Util_list.range(/* None */0, 10000)))
                                                              ]);
                                                    })
                                                ],
                                                /* :: */[
                                                  /* tuple */[
                                                    "filter works",
                                                    (function () {
                                                        return /* Eq */Block.__(0, [
                                                                  /* :: */[
                                                                    1,
                                                                    /* :: */[
                                                                      2,
                                                                      /* :: */[
                                                                        3,
                                                                        /* :: */[
                                                                          4,
                                                                          /* [] */0
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ],
                                                                  Util_list.filter((function (param) {
                                                                          return Caml_obj.caml_lessthan(0, param);
                                                                        }), /* :: */[
                                                                        -1,
                                                                        /* :: */[
                                                                          1,
                                                                          /* :: */[
                                                                            -2,
                                                                            /* :: */[
                                                                              2,
                                                                              /* :: */[
                                                                                3,
                                                                                /* :: */[
                                                                                  4,
                                                                                  /* :: */[
                                                                                    0,
                                                                                    /* [] */0
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ])
                                                                ]);
                                                      })
                                                  ],
                                                  /* :: */[
                                                    /* tuple */[
                                                      "filter doesn't cause stack overflow",
                                                      (function () {
                                                          return /* Eq */Block.__(0, [
                                                                    10000,
                                                                    Util_list.length(Util_list.filter((function (param) {
                                                                                return Caml_obj.caml_lessthan(0, param);
                                                                              }), Util_list.append(Util_list.replicate(10000, 1), Util_list.replicate(10000, 0))))
                                                                  ]);
                                                        })
                                                    ],
                                                    /* :: */[
                                                      /* tuple */[
                                                        "mapi works",
                                                        (function () {
                                                            return /* Eq */Block.__(0, [
                                                                      Util_list.range(/* Some */[-1], 3),
                                                                      Util_list.mapi((function (prim, prim$1) {
                                                                              return prim - prim$1 | 0;
                                                                            }), Util_list.replicate(4, 1))
                                                                    ]);
                                                          })
                                                      ],
                                                      /* :: */[
                                                        /* tuple */[
                                                          "mapi doesn't cause stack overflow",
                                                          (function () {
                                                              return /* Eq */Block.__(0, [
                                                                        10000,
                                                                        Util_list.length(Util_list.mapi((function (prim, prim$1) {
                                                                                    return prim + prim$1 | 0;
                                                                                  }), Util_list.replicate(10000, 1)))
                                                                      ]);
                                                            })
                                                        ],
                                                        /* :: */[
                                                          /* tuple */[
                                                            "map2 works",
                                                            (function () {
                                                                return /* Eq */Block.__(0, [
                                                                          Util_list.range(/* None */0, 4),
                                                                          Util_list.map2((function (prim, prim$1) {
                                                                                  return prim - prim$1 | 0;
                                                                                }), Util_list.range(/* Some */[1], 5), Util_list.replicate(4, 1))
                                                                        ]);
                                                              })
                                                          ],
                                                          /* :: */[
                                                            /* tuple */[
                                                              "map2 doesn't cause stack overflow",
                                                              (function () {
                                                                  return /* Eq */Block.__(0, [
                                                                            10000,
                                                                            Util_list.length(Util_list.map2((function (prim, prim$1) {
                                                                                        return prim + prim$1 | 0;
                                                                                      }), Util_list.replicate(10000, 1), Util_list.replicate(10000, 1)))
                                                                          ]);
                                                                })
                                                            ],
                                                            /* :: */[
                                                              /* tuple */[
                                                                "fold_right2 works",
                                                                (function () {
                                                                    var inc_mult_sub = function (x, y, z) {
                                                                      return Caml_int32.imul(x + 1 | 0, y) - z | 0;
                                                                    };
                                                                    return /* Eq */Block.__(0, [
                                                                              10,
                                                                              Util_list.fold_right2(inc_mult_sub, /* :: */[
                                                                                    1,
                                                                                    /* :: */[
                                                                                      2,
                                                                                      /* :: */[
                                                                                        3,
                                                                                        /* [] */0
                                                                                      ]
                                                                                    ]
                                                                                  ], /* :: */[
                                                                                    2,
                                                                                    /* :: */[
                                                                                      3,
                                                                                      /* :: */[
                                                                                        4,
                                                                                        /* [] */0
                                                                                      ]
                                                                                    ]
                                                                                  ], 1)
                                                                            ]);
                                                                  })
                                                              ],
                                                              /* :: */[
                                                                /* tuple */[
                                                                  "fold_right2 doesn't cause stack overflow",
                                                                  (function () {
                                                                      return /* Eq */Block.__(0, [
                                                                                20000,
                                                                                Util_list.fold_right2((function (a, b, c) {
                                                                                        return (a + b | 0) + c | 0;
                                                                                      }), Util_list.replicate(10000, 1), Util_list.replicate(10000, 1), 0)
                                                                              ]);
                                                                    })
                                                                ],
                                                                /* :: */[
                                                                  /* tuple */[
                                                                    "replicate works",
                                                                    (function () {
                                                                        return /* Eq */Block.__(0, [
                                                                                  Util_list.replicate(4, 1),
                                                                                  /* :: */[
                                                                                    1,
                                                                                    /* :: */[
                                                                                      1,
                                                                                      /* :: */[
                                                                                        1,
                                                                                        /* :: */[
                                                                                          1,
                                                                                          /* [] */0
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]);
                                                                      })
                                                                  ],
                                                                  /* :: */[
                                                                    /* tuple */[
                                                                      "replicate doesn't cause stack overflow",
                                                                      (function () {
                                                                          return /* Eq */Block.__(0, [
                                                                                    10000,
                                                                                    Util_list.length(Util_list.replicate(10000, 1))
                                                                                  ]);
                                                                        })
                                                                    ],
                                                                    /* :: */[
                                                                      /* tuple */[
                                                                        "some_option finds stuff",
                                                                        (function () {
                                                                            return /* Eq */Block.__(0, [
                                                                                      /* Some */[2],
                                                                                      Util_list.some_option(incr_if_pos, /* :: */[
                                                                                            -1,
                                                                                            /* :: */[
                                                                                              0,
                                                                                              /* :: */[
                                                                                                1,
                                                                                                /* :: */[
                                                                                                  4,
                                                                                                  /* [] */0
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ])
                                                                                    ]);
                                                                          })
                                                                      ],
                                                                      /* :: */[
                                                                        /* tuple */[
                                                                          "some_option doesn't find stuff",
                                                                          (function () {
                                                                              return /* Eq */Block.__(0, [
                                                                                        /* None */0,
                                                                                        Util_list.some_option(incr_if_pos, Util_list.replicate(4, -1))
                                                                                      ]);
                                                                            })
                                                                        ],
                                                                        /* :: */[
                                                                          /* tuple */[
                                                                            "some_option doesn't cause stack overflow",
                                                                            (function () {
                                                                                return /* Eq */Block.__(0, [
                                                                                          /* Some */[2],
                                                                                          Util_list.some_option(incr_if_pos, Util_list.append(Util_list.replicate(10000, 0), /* :: */[
                                                                                                    1,
                                                                                                    /* [] */0
                                                                                                  ]))
                                                                                        ]);
                                                                              })
                                                                          ],
                                                                          /* :: */[
                                                                            /* tuple */[
                                                                              "some finds stuff",
                                                                              (function () {
                                                                                  return /* Eq */Block.__(0, [
                                                                                            /* true */1,
                                                                                            Util_list.some((function (param) {
                                                                                                    return Caml_obj.caml_equal(1, param);
                                                                                                  }), Util_list.range(/* Some */[-1], 4))
                                                                                          ]);
                                                                                })
                                                                            ],
                                                                            /* :: */[
                                                                              /* tuple */[
                                                                                "some doesn't find stuff",
                                                                                (function () {
                                                                                    return /* Eq */Block.__(0, [
                                                                                              /* false */0,
                                                                                              Util_list.some((function (param) {
                                                                                                      return Caml_obj.caml_equal(1, param);
                                                                                                    }), Util_list.replicate(10, 0))
                                                                                            ]);
                                                                                  })
                                                                              ],
                                                                              /* :: */[
                                                                                /* tuple */[
                                                                                  "some doesn't cause stack overflow",
                                                                                  (function () {
                                                                                      return /* Eq */Block.__(0, [
                                                                                                /* true */1,
                                                                                                Util_list.some((function (param) {
                                                                                                        return Caml_obj.caml_equal(1, param);
                                                                                                      }), Util_list.append(Util_list.replicate(10000, 0), /* :: */[
                                                                                                          1,
                                                                                                          /* [] */0
                                                                                                        ]))
                                                                                              ]);
                                                                                    })
                                                                                ],
                                                                                /* :: */[
                                                                                  /* tuple */[
                                                                                    "all returns true",
                                                                                    (function () {
                                                                                        return /* Eq */Block.__(0, [
                                                                                                  /* true */1,
                                                                                                  Util_list.all((function (param) {
                                                                                                          return Caml_obj.caml_equal(1, param);
                                                                                                        }), Util_list.replicate(5, 1))
                                                                                                ]);
                                                                                      })
                                                                                  ],
                                                                                  /* :: */[
                                                                                    /* tuple */[
                                                                                      "all returns false",
                                                                                      (function () {
                                                                                          return /* Eq */Block.__(0, [
                                                                                                    /* false */0,
                                                                                                    Util_list.all((function (param) {
                                                                                                            return Caml_obj.caml_equal(1, param);
                                                                                                          }), /* :: */[
                                                                                                          1,
                                                                                                          /* :: */[
                                                                                                            1,
                                                                                                            /* :: */[
                                                                                                              1,
                                                                                                              /* :: */[
                                                                                                                0,
                                                                                                                /* :: */[
                                                                                                                  1,
                                                                                                                  /* [] */0
                                                                                                                ]
                                                                                                              ]
                                                                                                            ]
                                                                                                          ]
                                                                                                        ])
                                                                                                  ]);
                                                                                        })
                                                                                    ],
                                                                                    /* :: */[
                                                                                      /* tuple */[
                                                                                        "all doesn't cause stack overflow",
                                                                                        (function () {
                                                                                            return /* Eq */Block.__(0, [
                                                                                                      /* false */0,
                                                                                                      Util_list.all((function (param) {
                                                                                                              return Caml_obj.caml_equal(1, param);
                                                                                                            }), Util_list.append(Util_list.replicate(10000, 1), /* :: */[
                                                                                                                0,
                                                                                                                /* [] */0
                                                                                                              ]))
                                                                                                    ]);
                                                                                          })
                                                                                      ],
                                                                                      /* :: */[
                                                                                        /* tuple */[
                                                                                          "merge works",
                                                                                          (function () {
                                                                                              return /* Eq */Block.__(0, [
                                                                                                        /* :: */[
                                                                                                          1,
                                                                                                          /* :: */[
                                                                                                            2,
                                                                                                            /* :: */[
                                                                                                              2,
                                                                                                              /* :: */[
                                                                                                                3,
                                                                                                                /* :: */[
                                                                                                                  4,
                                                                                                                  /* :: */[
                                                                                                                    5,
                                                                                                                    /* [] */0
                                                                                                                  ]
                                                                                                                ]
                                                                                                              ]
                                                                                                            ]
                                                                                                          ]
                                                                                                        ],
                                                                                                        Util_list.merge(Caml_obj.caml_compare, /* :: */[
                                                                                                              1,
                                                                                                              /* :: */[
                                                                                                                2,
                                                                                                                /* :: */[
                                                                                                                  3,
                                                                                                                  /* :: */[
                                                                                                                    4,
                                                                                                                    /* [] */0
                                                                                                                  ]
                                                                                                                ]
                                                                                                              ]
                                                                                                            ], /* :: */[
                                                                                                              2,
                                                                                                              /* :: */[
                                                                                                                5,
                                                                                                                /* [] */0
                                                                                                              ]
                                                                                                            ])
                                                                                                      ]);
                                                                                            })
                                                                                        ],
                                                                                        /* :: */[
                                                                                          /* tuple */[
                                                                                            "merge doesn't cause stack overflow",
                                                                                            (function () {
                                                                                                return /* Eq */Block.__(0, [
                                                                                                          20000,
                                                                                                          Util_list.length(Util_list.merge(Caml_obj.caml_compare, Util_list.replicate(10000, 1), Util_list.replicate(10000, 1)))
                                                                                                        ]);
                                                                                              })
                                                                                          ],
                                                                                          /* :: */[
                                                                                            /* tuple */[
                                                                                              "range works with no start",
                                                                                              (function () {
                                                                                                  return /* Eq */Block.__(0, [
                                                                                                            /* :: */[
                                                                                                              0,
                                                                                                              /* :: */[
                                                                                                                1,
                                                                                                                /* :: */[
                                                                                                                  2,
                                                                                                                  /* :: */[
                                                                                                                    3,
                                                                                                                    /* :: */[
                                                                                                                      4,
                                                                                                                      /* [] */0
                                                                                                                    ]
                                                                                                                  ]
                                                                                                                ]
                                                                                                              ]
                                                                                                            ],
                                                                                                            Util_list.range(/* None */0, 5)
                                                                                                          ]);
                                                                                                })
                                                                                            ],
                                                                                            /* :: */[
                                                                                              /* tuple */[
                                                                                                "range works with start",
                                                                                                (function () {
                                                                                                    return /* Eq */Block.__(0, [
                                                                                                              /* :: */[
                                                                                                                2,
                                                                                                                /* :: */[
                                                                                                                  3,
                                                                                                                  /* :: */[
                                                                                                                    4,
                                                                                                                    /* :: */[
                                                                                                                      5,
                                                                                                                      /* [] */0
                                                                                                                    ]
                                                                                                                  ]
                                                                                                                ]
                                                                                                              ],
                                                                                                              Util_list.range(/* Some */[2], 6)
                                                                                                            ]);
                                                                                                  })
                                                                                              ],
                                                                                              /* :: */[
                                                                                                /* tuple */[
                                                                                                  "return is empty when start = stop",
                                                                                                  (function () {
                                                                                                      return /* Eq */Block.__(0, [
                                                                                                                /* [] */0,
                                                                                                                Util_list.range(/* Some */[1], 1)
                                                                                                              ]);
                                                                                                    })
                                                                                                ],
                                                                                                /* :: */[
                                                                                                  /* tuple */[
                                                                                                    "invalid range params return empty list",
                                                                                                    (function () {
                                                                                                        return /* Eq */Block.__(0, [
                                                                                                                  /* [] */0,
                                                                                                                  Util_list.range(/* Some */[5], 1)
                                                                                                                ]);
                                                                                                      })
                                                                                                  ],
                                                                                                  /* :: */[
                                                                                                    /* tuple */[
                                                                                                      "range doesn't cause stack overflow",
                                                                                                      (function () {
                                                                                                          return /* Eq */Block.__(0, [
                                                                                                                    10000,
                                                                                                                    Util_list.length(Util_list.range(/* None */0, 10000))
                                                                                                                  ]);
                                                                                                        })
                                                                                                    ],
                                                                                                    /* [] */0
                                                                                                  ]
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

Bs_mocha.from_pair_suites("Util.Option", /* :: */[
      /* tuple */[
        "map_default works on some",
        (function () {
            return /* Eq */Block.__(0, [
                      4,
                      Util_option.map_default(1, (function (param) {
                              return 1 + param | 0;
                            }), /* Some */[3])
                    ]);
          })
      ],
      /* :: */[
        /* tuple */[
          "map_default works on none",
          (function () {
              return /* Eq */Block.__(0, [
                        1,
                        Util_option.map_default(1, (function (param) {
                                return 1 + param | 0;
                              }), /* None */0)
                      ]);
            })
        ],
        /* :: */[
          /* tuple */[
            "is_some works on some",
            (function () {
                return /* Eq */Block.__(0, [
                          /* true */1,
                          Util_option.is_some(/* Some */[1])
                        ]);
              })
          ],
          /* :: */[
            /* tuple */[
              "is_some works on none",
              (function () {
                  return /* Eq */Block.__(0, [
                            /* false */0,
                            Util_option.is_some(/* None */0)
                          ]);
                })
            ],
            /* :: */[
              /* tuple */[
                "is_none works on some",
                (function () {
                    return /* Eq */Block.__(0, [
                              /* false */0,
                              Util_option.is_none(/* Some */[1])
                            ]);
                  })
              ],
              /* :: */[
                /* tuple */[
                  "is_none works on none",
                  (function () {
                      return /* Eq */Block.__(0, [
                                /* true */1,
                                Util_option.is_none(/* None */0)
                              ]);
                    })
                ],
                /* :: */[
                  /* tuple */[
                    "unwrap_exn works on some",
                    (function () {
                        return /* Eq */Block.__(0, [
                                  2,
                                  Util_option.unwrap_exn(/* Some */[2])
                                ]);
                      })
                  ],
                  /* :: */[
                    /* tuple */[
                      "unwrap_exn throws on none",
                      (function () {
                          return /* ThrowAny */Block.__(5, [(function () {
                                        return Util_option.unwrap_exn(/* None */0);
                                      })]);
                        })
                    ],
                    /* :: */[
                      /* tuple */[
                        "unwrap works on some",
                        (function () {
                            return /* Eq */Block.__(0, [
                                      2,
                                      Util_option.unwrap(3, /* Some */[2])
                                    ]);
                          })
                      ],
                      /* :: */[
                        /* tuple */[
                          "unwrap works on none",
                          (function () {
                              return /* Eq */Block.__(0, [
                                        3,
                                        Util_option.unwrap(3, /* None */0)
                                      ]);
                            })
                        ],
                        /* :: */[
                          /* tuple */[
                            "concat works",
                            (function () {
                                return /* Eq */Block.__(0, [
                                          /* :: */[
                                            1,
                                            /* :: */[
                                              2,
                                              /* :: */[
                                                3,
                                                /* :: */[
                                                  4,
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ],
                                          Util_option.concat(/* :: */[
                                                /* Some */[1],
                                                /* :: */[
                                                  /* None */0,
                                                  /* :: */[
                                                    /* Some */[2],
                                                    /* :: */[
                                                      /* Some */[3],
                                                      /* :: */[
                                                        /* None */0,
                                                        /* :: */[
                                                          /* None */0,
                                                          /* :: */[
                                                            /* Some */[4],
                                                            /* [] */0
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ])
                                        ]);
                              })
                          ],
                          /* :: */[
                            /* tuple */[
                              "concat doesn't cause stack overflow",
                              (function () {
                                  return /* Eq */Block.__(0, [
                                            10000,
                                            Util_list.length(Util_option.concat(Util_list.append(Util_list.replicate(10000, /* Some */[2]), Util_list.replicate(10000, /* None */0))))
                                          ]);
                                })
                            ],
                            /* :: */[
                              /* tuple */[
                                "map_concat works",
                                (function () {
                                    return /* Eq */Block.__(0, [
                                              /* :: */[
                                                2,
                                                /* :: */[
                                                  3,
                                                  /* :: */[
                                                    4,
                                                    /* :: */[
                                                      5,
                                                      /* [] */0
                                                    ]
                                                  ]
                                                ]
                                              ],
                                              Util_option.map_concat(incr_if_pos, /* :: */[
                                                    -1,
                                                    /* :: */[
                                                      1,
                                                      /* :: */[
                                                        -2,
                                                        /* :: */[
                                                          2,
                                                          /* :: */[
                                                            3,
                                                            /* :: */[
                                                              4,
                                                              /* :: */[
                                                                0,
                                                                /* [] */0
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ])
                                            ]);
                                  })
                              ],
                              /* :: */[
                                /* tuple */[
                                  "map_concat doesn't cause stack overflow",
                                  (function () {
                                      return /* Eq */Block.__(0, [
                                                10000,
                                                Util_list.length(Util_option.map_concat(incr_if_pos, Util_list.append(Util_list.replicate(10000, 1), Util_list.replicate(10000, 0))))
                                              ]);
                                    })
                                ],
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

exports.incr_if_pos = incr_if_pos;
/*  Not a pure module */
