// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

var Curry      = require("bs-platform/lib/js/curry.js");
var Util_list  = require("../common/util_list.js");
var Util_monad = require("../common/util_monad.js");

var l1 = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* [] */0
      ]
    ]
  ]
];

var l2 = /* :: */[
  5,
  /* :: */[
    6,
    /* :: */[
      7,
      /* :: */[
        8,
        /* [] */0
      ]
    ]
  ]
];

var res = Curry._2(Util_monad.List[/* >>= */1], l1, (function (v1) {
        return Curry._2(Util_monad.List[/* >>= */1], l2, (function (v2) {
                      return Curry._1(Util_monad.List[/* pure */2], v1 + v2 | 0);
                    }));
      }));

var res$prime = Curry._2(Util_monad.List[/* >>= */1], l1, (function (v1) {
        return Curry._2(Util_monad.List[/* =<< */6], (function (v2) {
                      return Curry._1(Util_monad.List[/* pure */2], v1 + v2 | 0);
                    }), l2);
      }));

console.log(res);

console.log(res$prime);

console.log(Util_list.length(res));

console.log(Util_list.length(Util_list.replicate(10, "a")));

exports.l1        = l1;
exports.l2        = l2;
exports.res       = res;
exports.res$prime = res$prime;
/* res Not a pure module */
