// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Page         = require("./page.js");
var Util         = require("../common/util/util.js");
var Curry        = require("bs-platform/lib/js/curry.js");
var Request      = require("../common/request.js");
var ReactDOMRe   = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact  = require("reason-react/lib/js/src/reasonReact.js");
var Util_promise = require("../common/util/util_promise.js");

function render(data) {
  return ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Page.make(data, /* array */[])), "base");
}

Curry._2(Util_promise.$less$$great, (function (param) {
        return Util.$percent((function (param) {
                      return Util.$percent(render, (function () {
                                    return /* () */0;
                                  }), param);
                    }), Util.debug, param);
      }), Request.get_html("/ban-data"));

exports.render = render;
/*  Not a pure module */
