// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Data         = require("../common/data.js");
var Page         = require("./page.js");
var Util         = require("../common/util/util.js");
var Curry        = require("bs-platform/lib/js/curry.js");
var Request      = require("../common/request.js");
var ReactDOMRe   = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact  = require("reason-react/lib/js/src/reasonReact.js");
var Util_option  = require("../common/util/util_option.js");
var Util_promise = require("../common/util/util_promise.js");

var default_data = /* record */[
  /* heroes : [] */0,
  /* details : [] */0,
  /* time */0
];

function render(data) {
  return ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Page.make(data, /* array */[])), "base");
}

var partial_arg = Data.Hero_data[/* from_json */0];

Curry._2(Util_promise.$less$$great, (function (param) {
        return Util.$percent((function (param) {
                      return Util.$percent(render, (function (param) {
                                    return Util_option.unwrap(default_data, param);
                                  }), param);
                    }), partial_arg, param);
      }), Request.get_json("/ban-data"));

exports.default_data = default_data;
exports.render       = render;
/*  Not a pure module */
