// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Page");

function make(data, _) {
  var handle_click = function (_, _$1, _$2) {
    console.log(data);
    return /* () */0;
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (_, self) {
      return React.createElement("div", {
                  onClick: Curry._1(self[/* handle */1], handle_click)
                }, "foo");
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
