// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Util      = require("./util/util.js");
var Curry     = require("bs-platform/lib/js/curry.js");
var Util_list = require("./util/util_list.js");

function map_el(f, c) {
  var res = [/* [] */0];
  var mapper = function (_, e) {
    res[0] = /* :: */[
      Curry._1(f, e),
      res[0]
    ];
    return /* () */0;
  };
  c.each(mapper);
  return Util_list.rev(res[0]);
}

function map(g, f, c) {
  return map_el((function (param) {
                return Util.$percent(f, (function (param) {
                              return g.call("", param);
                            }), param);
              }), c);
}

exports.map_el = map_el;
exports.map    = map;
/* Util_list Not a pure module */
