// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Curry        = require("bs-platform/lib/js/curry.js");
var Axios        = require("axios");
var Util_promise = require("./util/util_promise.js");

function get_json(s) {
  return Curry._2(Util_promise.$less$$great, (function (prim) {
                return prim.data;
              }), Axios.get(s));
}

function get_html(s) {
  return Curry._2(Util_promise.$less$$great, (function (prim) {
                return prim.data;
              }), Axios.get(s, ({"responseType": "text"})));
}

exports.get_json = get_json;
exports.get_html = get_html;
/* axios Not a pure module */
